version: '2'
services:

  gitea-server:
    container_name: gitea-server
    hostname: gitea-server
    image: gitea/gitea:latest
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "222:22"
